### PR TITLE
Take .clang-format from moveit

### LINKED ISSUE #72: Import `.clang_format` from MoveIt
For sake of consistency, we should just copy the exact [`.clang_format` from MoveIt](https://github.com/ros-planning/moveit/blob/master/.clang-format) and use it.

### PR DESCRIPTION
**Pull request by JStech**
Not that different, in the end. Closes #72.

### CODE REVIEW

**Review by schornakj — APPROVED** [review]
I read through the changes to `.clang-format` (and compared it to the original file linked in the issue), and I think this looks OK!

e: Other than the build/test CI steps, though I don't think that's limited to just this issue.

**Comment by tylerjw** [comment]
It looks like something is broken in the cache.  You'll need to go into the settings for this repo and delete the cache and run this again.

**Comment by rhaschke** [comment]
> You'll need to go into the settings for this repo and delete the cache and run this again.

So far, I haven't seen any possibility to delete the cache manually. Have you?

**Comment by tylerjw** [comment]
> So far, I haven't seen any possibility to delete the cache manually. Have you?

I thought there was a way to do this in the repo settings.  However it looks like this is not actually a feature and I'm probably just thinking of doing this in GitLab: https://github.com/actions/cache/issues/2

A workaround for that would be to add an arbitrary version to the cache prefix like `-v2` or something like that.

However looking more closely at this it seems that maybe there is something wrong with the melodic-source docker image that's causing this.

**Comment by JStech** [comment]
> However looking more closely at this it seems that maybe there is something wrong with the melodic-source docker image that's causing this.

It seems the `UNDERLAY` change isn't working as intended: #82

**Pull request merged**
